// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockDTORequest is an autogenerated mock type for the DTORequest type
type MockDTORequest[M any] struct {
	mock.Mock
	Field string `json:"field"`
}

type MockDTORequest_Expecter[M any] struct {
	mock  *mock.Mock
	Field string `json:"field"`
}

func (_m *MockDTORequest[M]) EXPECT() *MockDTORequest_Expecter[M] {
	return &MockDTORequest_Expecter[M]{mock: &_m.Mock}
}

// ToModel provides a mock function with no fields
func (_m *MockDTORequest[M]) ToModel() (M, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToModel")
	}

	var r0 M
	var r1 error
	if rf, ok := ret.Get(0).(func() (M, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() M); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(M)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDTORequest_ToModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToModel'
type MockDTORequest_ToModel_Call[M any] struct {
	*mock.Call
}

// ToModel is a helper method to define mock.On call
func (_e *MockDTORequest_Expecter[M]) ToModel() *MockDTORequest_ToModel_Call[M] {
	return &MockDTORequest_ToModel_Call[M]{Call: _e.mock.On("ToModel")}
}

func (_c *MockDTORequest_ToModel_Call[M]) Run(run func()) *MockDTORequest_ToModel_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDTORequest_ToModel_Call[M]) Return(_a0 M, _a1 error) *MockDTORequest_ToModel_Call[M] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDTORequest_ToModel_Call[M]) RunAndReturn(run func() (M, error)) *MockDTORequest_ToModel_Call[M] {
	_c.Call.Return(run)
	return _c
}

// NewMockDTORequest creates a new instance of MockDTORequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDTORequest[M any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDTORequest[M] {
	mock := &MockDTORequest[M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
