// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockDTORequest is an autogenerated mock type for the DTORequest type
type MockDTORequest struct {
	mock.Mock
}

type MockDTORequest_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDTORequest) EXPECT() *MockDTORequest_Expecter {
	return &MockDTORequest_Expecter{mock: &_m.Mock}
}

// ToModel provides a mock function with given fields: model
func (_m *MockDTORequest) ToModel(model any) error {
	ret := _m.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for ToModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDTORequest_ToModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToModel'
type MockDTORequest_ToModel_Call struct {
	*mock.Call
}

// ToModel is a helper method to define mock.On call
//   - model any
func (_e *MockDTORequest_Expecter) ToModel(model any) *MockDTORequest_ToModel_Call {
	return &MockDTORequest_ToModel_Call{Call: _e.mock.On("ToModel", model)}
}

func (_c *MockDTORequest_ToModel_Call) Run(run func(model any)) *MockDTORequest_ToModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockDTORequest_ToModel_Call) Return(_a0 error) *MockDTORequest_ToModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDTORequest_ToModel_Call) RunAndReturn(run func(any) error) *MockDTORequest_ToModel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDTORequest creates a new instance of MockDTORequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDTORequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDTORequest {
	mock := &MockDTORequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
