// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockDTOResponse is an autogenerated mock type for the DTOResponse type
type MockDTOResponse[M any] struct {
	mock.Mock
}

type MockDTOResponse_Expecter[M any] struct {
	mock *mock.Mock
}

func (_m *MockDTOResponse[M]) EXPECT() *MockDTOResponse_Expecter[M] {
	return &MockDTOResponse_Expecter[M]{mock: &_m.Mock}
}

// FromModel provides a mock function with given fields: model
func (_m *MockDTOResponse[M]) FromModel(model M) error {
	ret := _m.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for FromModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(M) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDTOResponse_FromModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromModel'
type MockDTOResponse_FromModel_Call[M any] struct {
	*mock.Call
}

// FromModel is a helper method to define mock.On call
//   - model M
func (_e *MockDTOResponse_Expecter[M]) FromModel(model interface{}) *MockDTOResponse_FromModel_Call[M] {
	return &MockDTOResponse_FromModel_Call[M]{Call: _e.mock.On("FromModel", model)}
}

func (_c *MockDTOResponse_FromModel_Call[M]) Run(run func(model M)) *MockDTOResponse_FromModel_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(M))
	})
	return _c
}

func (_c *MockDTOResponse_FromModel_Call[M]) Return(_a0 error) *MockDTOResponse_FromModel_Call[M] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDTOResponse_FromModel_Call[M]) RunAndReturn(run func(M) error) *MockDTOResponse_FromModel_Call[M] {
	_c.Call.Return(run)
	return _c
}

// NewMockDTOResponse creates a new instance of MockDTOResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDTOResponse[M any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDTOResponse[M] {
	mock := &MockDTOResponse[M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
