// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockDTOResponse is an autogenerated mock type for the DTOResponse type
type MockDTOResponse struct {
	mock.Mock
}

type MockDTOResponse_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDTOResponse) EXPECT() *MockDTOResponse_Expecter {
	return &MockDTOResponse_Expecter{mock: &_m.Mock}
}

// FromModel provides a mock function with given fields: model
func (_m *MockDTOResponse) FromModel(model any) error {
	ret := _m.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for FromModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDTOResponse_FromModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromModel'
type MockDTOResponse_FromModel_Call struct {
	*mock.Call
}

// FromModel is a helper method to define mock.On call
//   - model any
func (_e *MockDTOResponse_Expecter) FromModel(model any) *MockDTOResponse_FromModel_Call {
	return &MockDTOResponse_FromModel_Call{Call: _e.mock.On("FromModel", model)}
}

func (_c *MockDTOResponse_FromModel_Call) Run(run func(model any)) *MockDTOResponse_FromModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *MockDTOResponse_FromModel_Call) Return(_a0 error) *MockDTOResponse_FromModel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDTOResponse_FromModel_Call) RunAndReturn(run func(any) error) *MockDTOResponse_FromModel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDTOResponse creates a new instance of MockDTOResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDTOResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDTOResponse {
	mock := &MockDTOResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
