// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	zog "github.com/Oudwins/zog"
	mock "github.com/stretchr/testify/mock"
)

// MockDTOValidator is an autogenerated mock type for the DTOValidator type
type MockDTOValidator struct {
	mock.Mock
	Field  string `json:"field"`
	Field1 string `json:"field1"`
	Field2 string `json:"field2"`
}

type MockDTOValidator_Expecter struct {
	mock  *mock.Mock
	Field string `json:"field"`
}

func (_m *MockDTOValidator) EXPECT() *MockDTOValidator_Expecter {
	return &MockDTOValidator_Expecter{mock: &_m.Mock}
}

// Schema provides a mock function with no fields
func (_m *MockDTOValidator) Schema() *zog.StructSchema {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Schema")
	}

	var r0 *zog.StructSchema
	if rf, ok := ret.Get(0).(func() *zog.StructSchema); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zog.StructSchema)
		}
	}

	return r0
}

// MockDTOValidator_Schema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schema'
type MockDTOValidator_Schema_Call struct {
	*mock.Call
}

// Schema is a helper method to define mock.On call
func (_e *MockDTOValidator_Expecter) Schema() *MockDTOValidator_Schema_Call {
	return &MockDTOValidator_Schema_Call{Call: _e.mock.On("Schema")}
}

func (_c *MockDTOValidator_Schema_Call) Run(run func()) *MockDTOValidator_Schema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDTOValidator_Schema_Call) Return(_a0 *zog.StructSchema) *MockDTOValidator_Schema_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDTOValidator_Schema_Call) RunAndReturn(run func() *zog.StructSchema) *MockDTOValidator_Schema_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDTOValidator creates a new instance of MockDTOValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDTOValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDTOValidator {
	mock := &MockDTOValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
